-- ============================================================================
-- Seed Script: Populate lpk_list table
-- Source: list-lpk.csv (~457 records)
-- Run after migration 000013
-- ============================================================================

INSERT INTO lpk_list (name) VALUES
('LPK. BITODE WIRA INDONESIA'),
('LPK LIA CENTRAL JAYA'),
('LPK SOLUSI TERAMPIL GLOBAL'),
('Lpk Supit Urang Perkasa'),
('LPK Kochira Bali Indonesia'),
('LPK NAKAYOSHI GAKUIN CENTER'),
('LPK YUKI MULIA BERSAMA'),
('LPK MATAHARI NUSANTARA SENTOSA'),
('LPK Magita Jaya Perkasa'),
('LPK SHINJIRU MIRAI INDONESIA'),
('LPK Gunamandiri'),
('LPKS Kaizen Dharma Indonesia'),
('LENTERA'),
('LPK PUSAKA MULIA INSANI'),
('lpk asia your pratama'),
('LPK NEOJAPAN SOLUTION INDONESIA'),
('LPK FLORA TALENT INDONESIA'),
('Aichi Training Center'),
('LPK SHINORI INDONESIA CENTER'),
('INOVASI DELAPAN NUSANTARA'),
('LPK KISEKI MANDIRI'),
('KOBA MIRAI JAPAN'),
('PT. ARK JINZAI SOLUSI'),
('LPK TAKAHASHI INDONESIA'),
('LPK KIBOU KAFKA SEJAHTERA'),
('SUKAKU BERSAMA ABADI'),
('NOBORI SEIKO INDONESIA'),
('LPK JOSHAKHAPUTRI INDONESIA'),
('LPK TAKUMI'),
('LPK Audi Pratama Mandiri Indonesia'),
('PT Julian Indonesia Iwate'),
('LPK LPPR'),
('Yayasan Globalindo'),
('LPK. AISHIRO GAKUEN'),
('LPK Gakkou Citra Persada'),
('LPK GEMILANG PANDU ARTHA'),
('SHIAWASE LESTARI INDONESIA'),
('LPK KANADE INDONESIA BERKAH'),
('Mega Asia Cendekia'),
('LPK SATOSHI DAMARA INDONESIA'),
('Remindo Yume Utama'),
('PT.Ciremai Fuji Indonesia'),
('LPK Shinzou Panca Indonesia'),
('LPK SAKURA ANGKASA SEJAHTERA'),
('LPK Eda Kazoku'),
('LPK PURNA YUDHA PRAKASA'),
('LPK SHINICHI GAKUEN'),
('LPK Akari Eka Pratama'),
('LPK RSP TRAINING CENTER'),
('LPK SEKAI MUSTIKA'),
('LPK AOISORA SINAR INDONESIA'),
('LPK ASA COURSE INDONESIA'),
('LPK. NICHINI KAIGO SCHOOL'),
('LPK SERBAINDO'),
('LPK JI TRUST'),
('Generasi Putra Bangsa'),
('LPK ASAYAKA MAJU MULIA'),
('LPK Sahabat Jepang Indonesia'),
('LPK Zen Training Center'),
('LPK Orion Harmoni Mandala'),
('LPK JAPINDO KARAWANG'),
('LPK Mitra Maru Group'),
('LPK HARAPAN PUTERA INDONESIA'),
('Lpk Elpar Gakkou Indonesia'),
('LPK Bali International Tourism School'),
('LPK JOGJA KENSHU SENTA'),
('LPK.HIKARI INDONESIA'),
('LPK PT MJI EDUCATION SERVICE'),
('LPK TACHIBANA TRAINING CENTER'),
('LPK Higa Nusantara Jaya'),
('LPK SARI AGUNG ABADI JAYA'),
('LPK HIROKI KENSHU'),
('NGC EDUCATION CENTER'),
('LPK LOMBOK GLOBAL EDUCATION'),
('Okayama Toreningu Senta'),
('LPK DORYOUKU'),
('LPK Global Plan Management'),
('NCL Madiun'),
('PT TOYO MANDIRI'),
('Monarch Bali Gianyar'),
('LPK IGATE WORLD INDONESIA'),
('LPK INDONESIA KARIR AKADEMI'),
('LPK Difi Utama'),
('LPK KAIDOU GAKUIN'),
('LPK YAYASAN HINODE ABADI INDONESIA'),
('LPK PT ANUGERAH JAPAN INDONESIA (AJI)'),
('LPK HIKARI SUMUT'),
('LPK BAHANA INSPIRASI MUDA'),
('Ryoshin Harapan Edukasi'),
('NAWASENA'),
('LPK JAPAN MANDIRI INDONESIA'),
('LPK. PT KINKI SULTRA SINERGI'),
('LPK Momiji'),
('LPK YASUI ABADI'),
('LPK Bangkit Indonesia'),
('Celebrity International College'),
('LPK Ganesha Karya Abadi'),
('CIKARANG ACADEMY INDONESIA'),
('LPK SUBANG JAPANESE LANGUAGE CENTER'),
('LPK Mitra Jaya Indonesia'),
('LPK JINZIYA KLATEN INDONESIA'),
('PT HUMAN SELECT INDONESIA'),
('LPK JAPINDO CHIBA REFORMA'),
('LPK ANDALAN NUSANTARA'),
('Hotel and Cruise International (H.I)'),
('MITRA EDUKASI SUMBERDAYA'),
('LPK Saiko Singaraja'),
('LPK TSUNAGU BALI INTERNATIONAL'),
('LPK TRIMITRA MATAHARI MANDIRI'),
('LPK Hotaru'),
('LPK FURINKAZAN'),
('Bali Crystal College'),
('LPK Insan Mandiri Mediatama'),
('LPK Tiga Ksatria Indonesia'),
('AIRA NARSA JAPANESIA'),
('LPK JISCO INTERNATIONAL SCHOOL'),
('LPK GALANG SASTRA MANDALA'),
('LPK PT IMPIAN SEMESTA RAYA'),
('LPK MOGI ASIA PRIMA'),
('PT TORISE INDONESIA GLOBAL'),
('LPK JIEMA'),
('LPK INDONESIA DOURYU INDRAMAYU'),
('WISMA BERKAH SEJAHTERA'),
('lpk yayasan kiwari karya masagi'),
('LPK Yayasan Lengkong Kita Nuaya'),
('LPK KOKORONO SIJI'),
('KYOUDAI JAPANESE CORNER'),
('LPK SAKURA MEKAR'),
('LPK SHINSOU GAKKOU'),
('Nihon Sahabat Bersama'),
('LPK MULIA MEISOU INDONESIA'),
('LPK Yayasan Japan Technical Intern Trainee Support Center'),
('LPK Mitra Sarana Sejahtera'),
('LPK TAJI'),
('LPK Nippon Gate Indonesia'),
('LPK HIKARI JOGJA MANDIRI'),
('LPK PT MATAHARI BULAN JEPANG INDONESIA'),
('LPK Mirai International Mandiri'),
('LPK MUSHA KENDAL'),
('LPK Kyushu Manpower Indonesia'),
('LPK MENCETAK INSAN MANDIRI'),
('Kristika Mulia Sejahtera'),
('LPK Muda Berdaya Nusantara'),
('BINA NUSANTARA SEJAHTERA'),
('LPK. Mitra Duta Bali'),
('Asia Kyoei Center'),
('LPK Saporo Salsabila Sentosa'),
('LPK Jakaruta Global Group'),
('LPK GENKI KENSHU SENTA'),
('PSA Training and Career Partner'),
('PT. DAIMA AKADEMI NUSANTARA'),
('LPK HIBIKI ACADEMY'),
('LPK FUJI ACADEMY BALI'),
('LPK SHINTOMO GOLDEN INDONESIA'),
('LPK HINATA INDONESIA'),
('LPK Bakti Kencana Jaya Mulya'),
('LPK AKSELA'),
('DRAGON AICHI INDONESIA'),
('LPK HUMAIRA AKIRA INSTITUTE'),
('LPK TERAKOYA'),
('Logika Internasional'),
('LPK HIGASHI WAKAI INDONESIA'),
('LPK HANGGUK NIPPON BREBES'),
('PT. Wahana Danau Indah'),
('LPK JAYA INDONESIA BERKARYA'),
('LPKS BALI TOSHA LOMBOK KOCHI ( BTLK )'),
('LPK RANAH SAIYO SAKATO'),
('lpk asa merdeka'),
('lpk kuantum abadi mitra indonesia'),
('LPK Tunas Persada Indonesia'),
('LPK MIRAI NUSANTARA'),
('ONE CREATIVES INDONESIA'),
('LPK HIGLOB'),
('LPK KIZUNA MITRA INDONESIA'),
('PT.TACHI GAKKOU INTERNUSA'),
('NISHIDA GROUP INDONESIA'),
('WORLD HORENSO INDONESIA'),
('LPK BAHTERA MITRA UNGGULAN'),
('PT CAHAYA SUBARASHI INDONESIA'),
('LPK yayasan omotenashi'),
('LPK Jolly Roger International'),
('LEGACY INTERNATIONAL COLLEGE'),
('LPK Lingua Global Utama'),
('LPK CAP'),
('LPK PT BARAYA INDONESIA GLOBAL'),
('LPK RAFTEL SATYA INDONESIA'),
('LPK Aksa Arunika Abipraya'),
('LPK Midori Gakuin Center'),
('LPK JAPAN INTERSTUDY CENTER INDONESIA'),
('LPK Seihou Jaya Indonesia'),
('LPK Seikou Global Mandiri'),
('LPK MINNANO MIRAI ACADEMY'),
('LPK Semesta Indah Indonesia'),
('PT. Generasi Penerus Bangsa'),
('LPK NISHI JAWA JISSHU SENTA'),
('IROHA'),
('LPK ZURI S GAKKOU'),
('LPK TBS (TOTAL BALI SEJAHTERA)'),
('LPK DHARMAKERTA RAHARJA CIREBON'),
('LPK Hamana'),
('LPK Aska Bali'),
('LPK EIJI GLOBAL INDONESIA'),
('LPK Hikari Putra Mandiri'),
('LPK Karya Sejahtera Bersama'),
('BLP3 SDM Yokatta'),
('LPK Yayasan Jabung Makmur Perkasa'),
('LPK FUJI BIJAK PRESTASI'),
('LPK PUDJI UTAMI'),
('LPK Musubu'),
('LPK YAYASAN MATSUSHITA GOBEL'),
('Kaniva International'),
('Hashira Rizki Dunia'),
('LPK FUJISAN INDONESIA'),
('LPK PEMABA'),
('PT Harvest Man Indonesia'),
('LPK BHUMI IKA NUSWANTARA'),
('LPK Tsunagu Japan Indonesia'),
('LPK SEIKOU EDUCATION'),
('LPK MINORI MEDAN'),
('LPK SANTANE'),
('Momiji Padang Gakuin'),
('LPK UNIVERSAL LANGUAGE SKILLS'),
('KARYA SEMESTA SEJAHTERA'),
('LPK KAZOKU INDONESIA CENTER'),
('LPK KENJANI AMERTA INDONESIA'),
('LPK AZZAHRA'),
('LPK KIRANA INDONESIA'),
('LPK INOVASI CIPTA MANDIRI'),
('LPK ANGGREK INTERNATIONAL LANGUAGE COURSE'),
('PT. Mitra Bahari Indonesia'),
('LPK JAPAN INDONESIA ASAORI'),
('LPK LPJ BALI'),
('Homare Academy'),
('LPK.PT.Tatsuya Perkasa Singara'),
('LPK BIMA YOSHINDO HUTAMA'),
('LPK OSIN'),
('LPK OS SELNAJAYA INDONESIA'),
('Lembaga Pelatihan Kerja Darma (LPK DARMA)'),
('GLOBAL HARSU MANDIRI'),
('LPK Arashi JIC Bintang Pratama'),
('Lpk Nagano Language Center'),
('PT JITCA INDAH PRATAMA'),
('LPKS GAFU DREAM PARTNERS'),
('AQNESIA GLOBAL SOLO'),
('LPK KOTOBA CENTER CIREBON'),
('LPK JINET'),
('LPK KIBOUNOHIKARI INTERNASIONAL INDONESIA'),
('LPK YASRI'),
('LPK Caribbean International School'),
('LPK Sun Glory'),
('Yayasan Dwipayana Cipta Karya'),
('LPK Regisa Foundation'),
('LPK Jiritsu Nusantara'),
('LPK KAGAYAKI TRAINING CENTRE BANDUNG'),
('PT DELLA DING SHENG INDONESIA'),
('Yayasan Dwipahara'),
('LPK Chakra Dian Utama'),
('LPK Putri Yang Mandiri'),
('LPK SAKURA INDONESIA'),
('LPK PASIFIC MARINE HOTEL & CRUISESHIP SCHOOL'),
('LPK MEGUMI'),
('LPK HABATAKI'),
('LPK Budi Agung Binatara'),
('MIRAI MUKI INDONESIA'),
('KAMPUH WELDING INDONESIA'),
('LPK AKARI HARAPAN SRAGEN'),
('LPK BHASKORO TRAINING EDUCATION CENTRE'),
('LPK Hiro'),
('LPK Wiwitan Baru Sukabumi'),
('Sakura Artha Bhuwana'),
('LPK REKADAYA KARSA UTAMA'),
('CHUOO MANDIRI'),
('LPK JIRITSU'),
('LPK IWA KYO INDONESIA'),
('LPK CANGGIH BRASTEL INDONESIA'),
('LPK Borneo Raya Khatulistiwa'),
('PT INDRAMAYU KAN JAPAN'),
('SRI JAYA DWIPHA'),
('LPK HISHOU UNIVERSAL STYLE'),
('LEMBAGA PELATIHAN KERJA HAMAREN'),
('LPK Karunia Dewata'),
('Komatsu Training Center'),
('Jurusan Utama Nippon'),
('JIAEC'),
('LPK Candra Putra Lestari'),
('LPK Seiko Sukapura Indonesia'),
('LPK Bintang Darma Intama'),
('LPK SEKAI HIKARI INDONESIA'),
('LPK OISCA Indonesia'),
('Jaya Optima Tunas Orientasi'),
('LPK MITRA JINZAI INDONESIA'),
('LPK FUJI SUKSES MANDIRI NUSANTARA'),
('LPK TAIYOUKO GAKUIN CENTER'),
('LPK MATAHARI PERDANA'),
('LPK.MULIA MANDIRI INDONESIA'),
('LPK NAGOMI KAIGO GAKKO'),
('LPK PERMATA MUTIARA INDONESIA'),
('LPK DUTA SAHAYA'),
('LPK NOMURA INDONESIA'),
('LPKS RISKY BERKAH JAYA'),
('LPK YAYASAN SUNDAGAIYA'),
('LPK Suka Bagja Indonesia Jaya'),
('LPK MULIA UTAMA LOMBOK'),
('LPK MAHMUDI FUKUMOTO INDONESIA'),
('Masaru Skill Training'),
('LPK Putra Putri Indonesia'),
('LPK TOMONI MARAWA ABADI'),
('LPK YUTAKA MITRA INDONESIA'),
('LPK PT. ARIYO SURYANGGONO PERKASA'),
('LPK MARTANI'),
('LPK JAPAN INTERNASIONAL INDONESIA'),
('LPK Omoiyari Permata Indonesia'),
('LPK ANDALAN MITRA PRESTASI'),
('PT INTERNASIONAL PERSONEL MANAJEMEN INDONESIA'),
('OTC BALI GIANYAR'),
('Yayasan Jissho'),
('LPK AL FADANI'),
('LPKS BINTANG INDO CORPORA'),
('LPK MAU YAKIN BISA'),
('Lpk Hideaki Kabupaten Pemalang'),
('HIROTRUST TRAINING CENTRE'),
('CAHAYA MANDIRI INDONESIA'),
('LPK Kiyoraka Asia Global'),
('LPK MASAYUKI MITRA UTAMA'),
('LPK ASTA KARYA'),
('LPKS Shankara'),
('BINTANG HIGASHI JAVA'),
('LPK ORINES'),
('LPK Jinzai Servis Indonesia'),
('LPK SHINCHOKU INDONESIA'),
('LPK GLOBAL ICHSAN MANDIRI'),
('LPKS WORLD TRAINING CENTER PEMAGANGAN KE JEPANG'),
('LPK Prima Duta Sejati'),
('NEPMA LENTERA INDONESIA'),
('Indonesia Japan Development Work of Skill'),
('PT. CHIKARA INDONESIA TANGGUH'),
('LPK PUTRA HARAPAN BANGSA'),
('LPK AIBOU INDONESIA'),
('Universal Japan Course'),
('LPK. Himawari'),
('LPK SAHARA (sahabat anak dan remaja kreatif)'),
('LPK Hadetama'),
('LPK Tsubame Japanese Language Training Center'),
('LPK JAPAN INDO PERKASA'),
('LPK KOKORO BREBES'),
('LPK MAMORU NIHONGO GAKKOU'),
('LPK LINK'),
('Sinar Makmur Jaya'),
('LPK Mentari Asa Bali'),
('LPKS MAGDY INDONESIA'),
('Lpk Global Mandiri Indonesia'),
('PT VIVA Cipta Mirai'),
('LPK INDONESIA JAPAN MUSUBI'),
('LPK JOJO INTERNASIONAL GROUP'),
('LPK Sumber Jasa Kreatif'),
('LPK PERWITA NUSARAYA'),
('Yayasan eru putra Indonesia'),
('PT. LPK AMARTA BANGUN INDONESIA'),
('PT JAPANNESIA LANGUAGE SCHOOL'),
('LPK Hoshi Gakuen Bali'),
('LPK MERAKI ASA KHATULISTIWA'),
('PT KIBI MOMOTARO INDONESIA'),
('LPK Sinar World Indonesia'),
('LPK LPB3A'),
('LPK CAHAYA DUTA BALI'),
('lpk teratai gogakuin'),
('PT. KENJI JAYA PUTRA'),
('Lpk Hikari Man Power'),
('LPK. Momiji Gakuen'),
('Credible College'),
('LPK MACCA INSPIRASI NUSANTARA'),
('PT LPK IKAPEKSI MITRA SINERGI'),
('LPK MATAHARI TERBIT'),
('LPK UCHUMARU'),
('LPK Japan Education Global'),
('LPK YUUKI SHORAI INDONESIA'),
('LPK Akihiro Yuki Edo'),
('LPK Global Asia Shakaindo'),
('LPK Midori Gakkou'),
('LPK. International Professional Institute'),
('LPK INDOGLOBAL DUTA MANDIRI'),
('LPK YAYASAN KASHIKOI JAPANESE TRAINING CENTER'),
('LPK EIKOU KAKEHASHI INDONESIA'),
('LPK SEKAI INDONESIA'),
('LPK JAPAN SUNDA KEREN'),
('LPK YOGA MUSTIKA PERSADA'),
('LPK SAKURA MITRA INTERNASIONAL'),
('LPK Entrust Lestari Indonesia'),
('LPK Sava Jaya Anugerah'),
('YAYASAN BINA GENERASI BANGSA (BGB FOUNDATION)'),
('LPK One Piece Indonesia'),
('PT GAPINDO GEMILANG PRESTASI INDONESIA'),
('LPK FUKUTOMI JAPANESE SCHOOL'),
('LPKS PALAPA MUDA INDONESIA'),
('PT JAPAN INDONESIA ALIANSI'),
('LPK Akari Jawa Indonesia'),
('LPK SHINRAI JAPAN INDONESIA'),
('LPK. Bintang Permata Nusa'),
('LPK Hikari Bali'),
('Kansha Indonesia Center'),
('LPK FUJIWARA JLC'),
('LPK NAGOYA COURSE CENTER'),
('Wadah Perintis Muda'),
('LPK TSUNAGARU INDONESIA'),
('LPK Cahaya Matahari Manado'),
('YAYASAN SHIN INDONESIA'),
('SAIKO JAYA SUKSES'),
('LPK SEIKOU AGENG'),
('LPK Taihou Fusion Organization Indonesia Japan'),
('LPK Kesuma Karya Bangsa'),
('LPK HIMAWARI INDONESIA JAYA'),
('LPK KEBUN'),
('LPK Japan Indonesia College'),
('LPK ELEMEN INTERNASIONAL PELANGI'),
('LPK SAREKAH INSAN ATAMA'),
('LPK BISTRA KENSHU SENTA'),
('LPK Indopuraja Teknika'),
('LPK Lintas Negeri'),
('LPK OKAGE MANDIRI'),
('KOKUSAI JINZAI SUPPORT'),
('LPK BINAWAN'),
('LPK MITRA BUDI LESTARI'),
('Training & Learning Center'),
('Brother training center'),
('LPK. SALUNGLUNG'),
('LPK Education Japan Center Indonesia'),
('LPK HARAPAN PUTERA BANDUNG INDONESIA'),
('LPK Buana Gogakuin'),
('LPK Global Alpha'),
('LPK MUGEN (Multi Generasi Indonesia)'),
('LPK Majesta Foundation'),
('LPK KACHI KOKORO'),
('LPK KARYA JAYA ABADI'),
('LPK KOCHI MAKMUR INDONESIA'),
('LPK YUTAKA EDUCATION CENTER'),
('PT OOSAKA GAKKOU'),
('LPK TJOKRO BAKTI.'),
('Tomo Graha Kirana'),
('LPK HAGUKUMI GAKUIN PADANG'),
('LPK. MANABU INSAN MULIA'),
('YAYASAN ISMOYO JATI BERSINAR'),
('LPK ADIPATI BHUMI BHAKTI'),
('Kizuna Wawonii Indonesia'),
('LPK NUSANTARA GAKKOU BANYUWANGI'),
('LPK BALI BINA MANDIRI')
ON CONFLICT (name) DO NOTHING;
